version: "3.1"

services:
  agent:
    image: grafana/agent:v0.23.0
    volumes:
      - ./agent:/etc/agent-config
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/config.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: host.docker.internal:8900
      OAUTH_CLIENT_ID: $AGENT_CLIENT_ID
      OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
      OAUTH_TOKEN_URL: $OAUTH_TOKEN_URL
      OAUTH_AUDIENCE: $OAUTH_AUDIENCE
      BEARER_TOKEN: $BEARER_TOKEN
    ports:
      - "12345:12345"
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    user: "104"
    ports:
      - 3000:3000
    restart: always
