apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-gateway.fullname" . }}
  labels:
    {{- include "mimir-gateway.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4}}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mimir-gateway.selectorLabels" . | nindent 4 }}
