name: Test and Lint

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.2"

      - name: Format Check
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m

      - name: Run Tests
        run: go test -v ./...
